language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - npm run build:travis

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

after_success:
  - ./deploy/qshell account $AK $SK liyang
  - ./deploy/qshell qupload ./deploy/upload.conf
  - ./deploy/qshell cdnrefresh --dirs -i ./deploy/cdnrefresh.txt