language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"

branches:
  only:
  - master

script:
  - npm run build:travis

before_install:
  - ./qshell account $AK $SK $NAME
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

after_success:
  - ./qshell listbucket d2-admin-start-kit -o cdn-files.txt
  - ./qshell batchdelete --force d2-admin-start-kit -i cdn-files.txt
  - ./qshell qupload qiniu-config
  - ./qshell cdnrefresh -dirs cdnrefresh-dirs.txt